apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-backup-pvc
  namespace: itip-en-05
  labels:
    app.kubernetes.io/part-of: frontend-en-05
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
