ALTER TABLE fire_events ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE fire_events ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE fire_events ADD COLUMN IF NOT EXISTS location_accuary_m INTEGER;
