ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS accuracy_m DOUBLE PRECISION;
